default_platform(:ios)

platform :ios do
  desc "Build iOS Release app"
  lane :e2e_tests do
    sh("npm install")

    cocoapods

    gym(
      scheme: "weatherApp",
      configuration: "Release",
      skip_package_ipa: true,
      skip_codesigning: true,
      destination: "generic/platform=iOS Simulator",
    )

    UI.success("Build completed")
  end
end
