default_platform(:ios)

platform :ios do
  desc "Build iOS Release app"
  lane :build do

    gym(
      scheme: "weatherApp",
      configuration: "Release",
      skip_package_ipa: true,
      skip_codesigning: true,
      clean: true,
      destination: "generic/platform=iOS Simulator",
    )

    UI.success("Build completed")
  rescue => e
    UI.error("Failed to build the app: #{e}")
    raise e
  end
end
