default_platform(:ios)

platform :ios do
  desc "Build iOS Release app"
  lane :e2e_tests do
    sh("npm install")

    cocoapods

    xcodebuild(
      configuration: "Release",
      scheme: "weatherApp",
      workspace: "weatherApp.xcworkspace",
      xcargs: "-quiet -sdk 'iphonesimulator' -destination 'generic/platform=iOS Simulator'",
      derivedDataPath: "ios/build"
    )

  end
end
