default_platform(:android)

platform :android do
  desc "Increment build version"
  lane :increment_version do
    latest_release = firebase_app_distribution_get_latest_release(
      app: "1:408904905285:android:0e4314358215409b48292c"
    )

    if latest_release.nil?
      UI.message("No previous release found. Setting version code to 1.")
      version_code = 1
    else
      version_code = latest_release[:buildVersion].to_i + 1
    end

    increment_version_code(version_code: version_code)
  end

  desc "Distribute the app to Firebase"
  lane :distribute do
    gradle(task: 'clean assembleRelease', project_dir: '.', print_command: false, properties: {})

    firebase_app_distribution(
      app: "1:408904905285:android:0e4314358215409b48292c",
      testers: "bataevvlad@gmail.com, vladislav.bataev@callstack.com",
      release_notes: "New amazing build!"
    )
  end

  desc "Full pipeline: Increment version and distribute"
  lane :release do
    increment_version
    distribute
  end
end
