default_platform(:android)

platform :android do
  desc "Build the Android app"
  lane :build do

    begin
      gradle(
        task: "assembleRelease"
      )
      UI.success("Build completed successfully 🚀")
    rescue => e
      UI.error("Failed to build the app: #{e}")
      raise e
    end
  end
end
