name: Build release without signing - iOS
run-name: ${{ github.actor }} is build release without signing - iOS 🚀

on:
  pull_request:
    branches: ['main']

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: Get npm cache directory path
        id: npm-cache-dir-path
        run: echo "::set-output name=dir::$(npm config get cache)"

      - uses: actions/cache@v2
        id: npm-cache
        with:
          path: ${{ steps.npm-cache-dir-path.outputs.dir }}
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - uses: actions/cache@v2
        with:
          path: ios/Pods
          key: ${{ runner.os }}-pods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-pods-

      - name: Install Dependencies
        run: npm install

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.3.4
          bundler: 2.5.11

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
        working-directory: ios

      - name: Install CocoaPods
        run: |
          npx pod-install --quiet
        working-directory: ios

      - name: Run Fastlane build
        run: bundle exec fastlane build
        working-directory: ios
