name: Build and upload to Maestro Cloud

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 120

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Clean Build Folder
        run: xcodebuild clean -workspace 'ios/weatherApp.xcworkspace' -scheme 'weatherApp'

      - name: Install CocoaPods
        run: pod install --verbose
        working-directory: ios

      - name: Build iOS app with verbose logging
        run: |
          set -o pipefail &&
          xcodebuild build \
            -workspace 'ios/weatherApp.xcworkspace' \
            -scheme 'weatherApp' \
            -configuration Debug \
            -destination 'generic/platform=iOS Simulator' \
            CONFIGURATION_BUILD_DIR=$PWD/build \
            -UseNewBuildSystem=YES \
            -verbose | tee build.log | xcpretty

      - name: Save Xcode logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: xcode-build-log
          path: build.log

      - name: Upload to Maestro Cloud
        uses: mobile-dev-inc/action-maestro-cloud@v1.1.0
        with:
          name: 'Build 0.0.1'
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: build/weatherApp.app
