name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: macos-12

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Run ESLint
        run: npm run lint

      - name: Run Jest tests
        run: npm test -- --coverage

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'

      - name: Set up iOS Simulator
        uses: futureware-tech/simulator-action@v2
        with:
          model: 'iPhone 14 Pro'

      - name: Run Maestro tests
        uses: dniHze/maestro-test-action@v1
        with:
          flow: .maestro
          report: maestro/report.xml
