name: e2e Android Tests
run-name: ${{ github.actor }} is running e2e Android Tests 🚀

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      app: app/build/outputs/apk/debug

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'

      - name: Make gradlew executable
        run: cd android && chmod +x ./gradlew

      - run: cd android && ./gradlew assembleRelease

      - uses: mobile-dev-inc/action-maestro-cloud@v1
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: android/app/build/outputs/apk/release/app-release.apk
          workspace: .maestro/android/
