name: e2e iOS Tests
run-name: ${{ github.actor }} is running e2e iOS Tests 🚀

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    timeout-minutes: 120

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.10
          bundler: 1.17.2

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install
        working-directory: ios

      - name: Install CocoaPods
        run: bundle exec pod install --verbose
        working-directory: ios

      - name: Run Fastlane E2E Tests
        run: bundle exec fastlane e2e_tests
        working-directory: ios
        env:
          MAESTRO_CLOUD_API_KEY: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
