name: e2e Android Tests
run-name: ${{ github.actor }} is running e2e Android Tests 🚀

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      app: app/build/outputs/apk/debug

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make gradlew executable
        run: cd android && chmod +x ./gradlew

      - name: Build Android app
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Upload to Maestro Cloud
        uses: mobile-dev-inc/action-maestro-cloud@v1.7.0
        with:
          api-key: ${{ secrets.MAESTRO_CLOUD_API_KEY }}
          app-file: android/app/build/outputs/apk/release/app-release.apk
          workspace: .maestro/android/
